version: "3.8"

services:

  mysql:
    image: mysql:8.1.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test1234!
      - MYSQL_DATABASE=reactlibrarydatabase
    volumes:
      - ./mysql/init/1.sql:/docker-entrypoint-initdb.d/1.sql
      - ./mysql/init/2.sql:/docker-entrypoint-initdb.d/2.sql
      - ./mysql/init/3.sql:/docker-entrypoint-initdb.d/3.sql
      - ./mysql/init/4.sql:/docker-entrypoint-initdb.d/4.sql
      - ./mysql/init/5.sql:/docker-entrypoint-initdb.d/5.sql
      - ./mysql/init/6.sql:/docker-entrypoint-initdb.d/6.sql
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"

  keycloak-postgres:
    image: postgres:15.3
    container_name: keycloak_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: "pg_isready -U postgres"

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak-postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
      - KC_HEALTH_ENABLED=true
    ports:
      - "8080:8080"
    command: start-dev
    depends_on:
      - keycloak-postgres
    healthcheck:
      test: "curl -f http://localhost:8080/health/ready || exit 1"