name: Commit Stage
on: push

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: greeta-bookshop-01
  VERSION: ${{ github.sha }}

jobs:
  package:
    name: Package and Publish
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Build
        run: |
          mvn clean install
      - name: Build container images
        run: |
          cd catalog-service
          mvn spring-boot:build-image -DskipTests \
            -Dspring-boot.build-image.imageName=${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/catalog-service:${{ env.VERSION }}
          cd ../
          cd order-service
          mvn spring-boot:build-image -DskipTests \
            -Dspring-boot.build-image.imageName=${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/order-service:${{ env.VERSION }}
          cd ../
          cd dispatcher-service
          mvn spring-boot:build-image -DskipTests \
            -Dspring-boot.build-image.imageName=${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/dispatcher-service:${{ env.VERSION }}
          cd ../
          cd gateway-service
          mvn spring-boot:build-image -DskipTests \
            -Dspring-boot.build-image.imageName=${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/gateway-service:${{ env.VERSION }}

      - name: Log into container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish container image
        run:  |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/catalog-service:${{ env.VERSION }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/order-service:${{ env.VERSION }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/dispatcher-service:${{ env.VERSION }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/gateway-service:${{ env.VERSION }}
      - name: Publish container image (latest)
        run: |
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/catalog-service:${{ env.VERSION }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/catalog-service:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/catalog-service:latest
          
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/order-service:${{ env.VERSION }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/order-service:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/order-service:latest
          
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/dispatcher-service:${{ env.VERSION }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/dispatcher-service:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/dispatcher-service:latest
                    
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/gateway-service:${{ env.VERSION }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/gateway-service:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/gateway-service:latest